module.exports = {
  displayName: 'Backend Unit Tests',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '../src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/*.interface.ts',
    '!**/*.dto.ts',
    '!**/*.module.ts',
    '!**/main.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/*.d.ts',
    '!**/reference/**',
    '!**/migrations/**'
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 2,
      functions: 3,
      lines: 8,
      statements: 9,
    },
  },
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@modules/(.*)$': '<rootDir>/modules/$1',
    '^@integrations/(.*)$': '<rootDir>/integrations/$1',
    '^@infrastructure/(.*)$': '<rootDir>/infrastructure/$1',
    '^@shared/(.*)$': '<rootDir>/shared/$1',
    '^src/(.*)$': '<rootDir>/$1',
    '^lib/(.*)$': '<rootDir>/../lib/$1',
    '^dto/(.*)$': '<rootDir>/dto/$1',
    '^interfaces/(.*)$': '<rootDir>/interfaces/$1',
    '^reference/(.*)$': '<rootDir>/reference/$1',
    '^test/(.*)$': '<rootDir>/../test/$1',
  },
  modulePaths: ['<rootDir>/../'],
  setupFilesAfterEnv: ['<rootDir>/../test/setup.ts'],
  testTimeout: 30000,
  maxWorkers: 1,
  verbose: true,
};