module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '../..',
  testEnvironment: 'node',
  testRegex: '/test/api/.*\\.(test|spec)\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.module.ts',
    '!src/main.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.entity.ts',
  ],
  coverageDirectory: 'coverage/api',
  testTimeout: 30000,
  setupFilesAfterEnv: ['<rootDir>/test/api/setup.ts'],
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@common/(.*)$': '<rootDir>/src/common/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@integrations/(.*)$': '<rootDir>/src/integrations/$1',
    '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^lib/(.*)$': '<rootDir>/src/lib/$1',
    '^dto/(.*)$': '<rootDir>/src/dto/$1',
    '^interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^reference/(.*)$': '<rootDir>/src/reference/$1',
    '^shared/(.*)$': '<rootDir>/src/shared/$1',
    '^decorators/(.*)$': '<rootDir>/src/decorators/$1',
    '^filters/(.*)$': '<rootDir>/src/filters/$1',
    '^guards/(.*)$': '<rootDir>/src/guards/$1',
    '^interceptors/(.*)$': '<rootDir>/src/interceptors/$1',
    '^middleware/(.*)$': '<rootDir>/src/middleware/$1',
    '^pipes/(.*)$': '<rootDir>/src/pipes/$1',
  },
};