version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ante-postgres
    environment:
      POSTGRES_USER: ante
      POSTGRES_PASSWORD: ante_password
      POSTGRES_DB: ante_db
      TZ: Asia/Manila
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ante-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ante"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ante-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ante-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: ante-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: jdev
      MONGO_INITDB_ROOT_PASSWORD: water123
      MONGO_INITDB_DATABASE: ante-test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ante-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  ante-network:
    driver: bridge