export default [
  {
    abb: 'PR',
    key: 'PURCHASE_REQUEST',
    label: 'Purchase Request',
    module: 'purchase-order',
    itemImpact: 'non-posting',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'PO',
    key: 'PURCHASE_ORDER',
    label: 'Purchase Order',
    module: 'purchase-order',
    itemImpact: 'incrementing',
    moneyImpact: 'create-payable',
  },
  {
    abb: 'RI',
    key: 'REFILL_INVENTORY',
    label: 'Inventory Refill',
    module: 'inventory',
    itemImpact: 'incrementing',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'WI',
    key: 'WRITEOFF_INVENTORY',
    label: 'Inventory Writeoff',
    module: 'inventory',
    itemImpact: 'deducting',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'WTS',
    key: 'TRANSFER_INVENTORY_FROM',
    label: 'Warehouse Transfer (Send)',
    module: 'inventory',
    itemImpact: 'deducting',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'ITL',
    key: 'IN_TRANSIT_LOADED',
    label: 'Truck Load Receipt',
    module: 'inventory',
    itemImpact: 'incrementing',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'ITU',
    key: 'IN_TRANSIT_UNLOADED',
    label: 'Truck Unload Receipt',
    module: 'inventory',
    itemImpact: 'deducting',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'DEL',
    key: 'ITEM_DELIVERED',
    label: 'Delivery Receipt',
    module: 'inventory',
    itemImpact: 'incrementing',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'FDD',
    key: 'FOR_DELIVERY_DEDUCTION',
    label: 'Loaded to Truck',
    module: 'inventory',
    itemImpact: 'deducting',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'FDI',
    key: 'FOR_DELIVERY_INCREMENT',
    label: 'Delivery Ready',
    module: 'inventory',
    itemImpact: 'incrementing',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'RET',
    key: 'RESERVED_FOR_TRANSFER',
    label: 'Reserved for Transfer',
    module: 'inventory',
    itemImpact: 'incrementing',
    moneyImpact: 'non-posting',
  },
  {
    abb: 'WTR',
    key: 'TRANSFER_INVENTORY_TO',
    label: 'Warehouse Transfer (Receive)',
    module: 'inventory',
    itemImpact: 'incrementing',
    moneyImpact: 'non-posting',
  },
];
