export default [
  {
    key: 'PAYMENT_APPROVAL',
    label: 'Payment Approval',
    approveButton: 'Approve Payment',
    rejectButton: 'Reject Payment',
    requiredFundAccount: false,
    backgroundColor: 'orange',
    color: 'white',
    nextStage: 'PREPARATION',
  },
  {
    key: 'PREPARATION',
    label: 'Preparation',
    approveButton: 'Preparation Done',
    rejectButton: null,
    requiredFundAccount: false,
    backgroundColor: 'orange',
    color: 'white',
    nextStage: 'RELEASE_APPROVAL',
  },
  {
    key: 'RELEASE_APPROVAL',
    label: 'Release Approval',
    approveButton: 'Approve Release',
    rejectButton: 'Reject Release',
    requiredFundAccount: false,
    backgroundColor: 'green',
    color: 'white',
    nextStage: 'FOR_RELEASING',
  },
  {
    key: 'FOR_RELEASING',
    label: 'For Releasing',
    approveButton: 'Payment Released',
    rejectButton: null,
    requiredFundAccount: true,
    backgroundColor: 'green',
    color: 'white',
    nextStage: 'PAYMENT_RELEASED',
  },
  {
    key: 'PAYMENT_RELEASED',
    label: 'Released',
    approveButton: null,
    rejectButton: null,
    requiredFundAccount: false,
    backgroundColor: 'blue',
    color: 'white',
    nextStage: null,
  },
  {
    key: 'REJECTED',
    label: 'Rejected',
    approveButton: null,
    rejectButton: null,
    requiredFundAccount: false,
    backgroundColor: 'red',
    color: 'white',
    nextStage: null,
  },
];
