import { ScopeList } from '@prisma/client';
import { ScopeDataResponse } from '../shared/response/scope.response';
import { SystemModule } from '../shared/enums/user-level.enums';

enum ScopeType {
  PAGE = 'PAGE',
  SUBPAGE = 'SUBPAGE',
  BUTTON = 'BUTTON',
  WIDGET = 'WIDGET',
}

interface AIServiceAccess {
  availableServices: string[];
  aiProviders: string[];
  contextDescription?: string;
}

const ScopeReference: (ScopeDataResponse & {
  module: SystemModule;
  aiServices?: AIServiceAccess;
})[] = [
  {
    id: ScopeList.MANPOWER_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Manpower',
    description: 'Allows access to the manpower page.',
    module: SystemModule.MANPOWER,
    aiServices: {
      availableServices: [
        'getEmployeeList',
        'getTimekeepingSummary',
        'getPayrollStatus',
      ],
      aiProviders: ['gemini', 'openai'],
      contextDescription:
        'AI can access employee data, timekeeping information, and payroll summaries',
    },
  },
  {
    id: 'MANPOWER_PAYROLL' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.MANPOWER_ACCESS,
    name: 'Payroll',
    description: 'Payroll related features',
    module: SystemModule.MANPOWER,
  },
  {
    id: 'MANPOWER_TEAM' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.MANPOWER_ACCESS,
    name: 'Team',
    description: 'Team management features',
    module: SystemModule.MANPOWER,
  },
  {
    id: 'MANPOWER_TIMEKEEPING_LOGS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.MANPOWER_ACCESS,
    name: 'Timekeeping Logs',
    description: 'Time tracking and logging features',
    module: SystemModule.MANPOWER,
  },
  {
    id: 'MANPOWER_CONFIGURATION' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.MANPOWER_ACCESS,
    name: 'Configuration',
    description: 'Configuration settings for manpower module',
    module: SystemModule.MANPOWER,
  },
  {
    id: 'MANPOWER_REPORTS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.MANPOWER_ACCESS,
    name: 'Reports',
    description: 'Reports for manpower module',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_HRIS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.MANPOWER_ACCESS,
    name: 'Manpower HRIS',
    description: 'Allows access to the manpower HRIS page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_IMPORTATION_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_TIMEKEEPING_LOGS' as any,
    name: 'Manpower Time Importation',
    description: 'Allows access to the manpower time importation page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_HRIS_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_HRIS_ACCESS,
    name: 'HRIS Create',
    description: 'Allows create access to the manpower HRIS page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_HRIS_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_HRIS_ACCESS,
    name: 'HRIS Update',
    description: 'Allows update access to the manpower HRIS page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_HRIS_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_HRIS_ACCESS,
    name: 'HRIS Delete',
    description: 'Allows delete access to the manpower HRIS page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_PAYROLL' as any,
    name: 'Payroll Center',
    description: 'Allows access to the manpower payroll center page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_PAYSLIP_CENTER_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_PAYROLL' as any,
    name: 'Payslip Center',
    description: 'Allows access to the manpower payslip center page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TEAM_ATTENDANCE_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_TEAM' as any,
    name: 'Team Attendance',
    description: 'Allows access to the team attendance page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TEAM_SHIFTS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_TEAM' as any,
    name: 'Team Shifting Management',
    description: 'Allows access to the team shifting management page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_DEVICE_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_TIMEKEEPING_LOGS' as any,
    name: 'Time Keeping Device',
    description: 'Allows access to the time keeping device page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_PAYROLL_SUBMIT_FOR_REVIEW,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
    name: 'Submit for Review',
    description:
      'Allows submit for review access to the manpower payroll page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_PAYROLL_PROCESS_FOR_REVIEW,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
    name: 'Process for Review',
    description:
      'Allows process for review access to the manpower payroll page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_PAYROLL_SUBMIT_POSTING,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
    name: 'Submit Posting',
    description: 'Allows submit posting access to the manpower payroll page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Payroll Group Configuration',
    description: 'Allows access to the payroll group configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group Create',
    description: 'Allows create access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group Update',
    description: 'Allows update access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group Delete',
    description: 'Allows delete access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Local Holiday Configuration',
    description: 'Allows access to the local holiday configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_ACCESS,
    name: 'Local Holiday Create',
    description: 'Allows create access to the local holiday configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_ACCESS,
    name: 'Local Holiday Update',
    description: 'Allows update access to the local holiday configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_ACCESS,
    name: 'Local Holiday Delete',
    description: 'Allows delete access to the local holiday configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'National Holiday Configuration',
    description: 'Allows access to the national holiday configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_ACCESS,
    name: 'National Holiday Create',
    description: 'Allows create access to the national holiday configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_ACCESS,
    name: 'National Holiday Update',
    description: 'Allows update access to the national holiday configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_ACCESS,
    name: 'National Holiday Delete',
    description: 'Allows delete access to the national holiday configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SERVICE_INCLUSIVE_LEAVE_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Service Incentive Leaves',
    description:
      'Allows access to the service incentive leave configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Payroll Approvers Configuration',
    description: 'Allows access to the payroll approvers configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_ACCESS,
    name: 'Payroll Approvers Create',
    description: 'Allows create access to the payroll approvers configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_ACCESS,
    name: 'Payroll Approvers Update',
    description: 'Allows update access to the payroll approvers configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_ACCESS,
    name: 'Payroll Approvers Delete',
    description: 'Allows delete access to the payroll approvers configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Schedule Configuration',
    description: 'Allows access to the schedule configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_ACCESS,
    name: 'Schedule Create',
    description: 'Allows create access to the schedule configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_ACCESS,
    name: 'Schedule Update',
    description: 'Allows update access to the schedule configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_ACCESS,
    name: 'Schedule Delete',
    description: 'Allows delete access to the schedule configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SHIFT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Shift Configuration',
    description: 'Allows access to the shift configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SHIFT_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_SHIFT_ACCESS,
    name: 'Shift Create',
    description: 'Allows create access to the shift configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SHIFT_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_SHIFT_ACCESS,
    name: 'Shift Update',
    description: 'Allows update access to the shift configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SHIFT_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_SHIFT_ACCESS,
    name: 'Shift Delete',
    description: 'Allows delete access to the shift configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Deduction Configuration',
    description: 'Allows access to the deduction configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_ACCESS,
    name: 'Deduction Create',
    description: 'Allows create access to the deduction configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_ACCESS,
    name: 'Deduction Update',
    description: 'Allows update access to the deduction configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_ACCESS,
    name: 'Deduction Delete',
    description: 'Allows delete access to the deduction configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Allowance Configuration',
    description: 'Allows access to the allowance configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_ACCESS,
    name: 'Allowance Create',
    description: 'Allows create access to the allowance configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_ACCESS,
    name: 'Allowance Update',
    description: 'Allows update access to the allowance configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_ACCESS,
    name: 'Allowance Delete',
    description: 'Allows delete access to the allowance configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Cutoff Configuration',
    description: 'Allows access to the cutoff configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_CREATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_ACCESS,
    name: 'Cutoff Create',
    description: 'Allows create access to the cutoff configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_UPDATE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_ACCESS,
    name: 'Cutoff Update',
    description: 'Allows update access to the cutoff configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_DELETE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_CUTOFF_ACCESS,
    name: 'Cutoff Delete',
    description: 'Allows delete access to the cutoff configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_PAYROLL' as any,
    name: 'Time Keeping (All Branch)',
    description: 'Allows access to all branch time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_BY_BRANCH,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_PAYROLL' as any,
    name: 'Time Keeping (By Branch)',
    description: 'Allows access to time keeping by branch.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_CREATE_RAW_LOGS,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    name: 'Create Raw Logs',
    description: 'Allows creation of raw logs in time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_DELETE_RAW_LOGS,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    name: 'Delete Raw Logs',
    description: 'Allows deletion of raw logs in time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_EDIT_TIME,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    name: 'Edit Time',
    description: 'Allows editing of time in time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_APPROVE_REST_DAY,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    name: 'Approve Rest Day',
    description: 'Allows approval of rest day in time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_APPROVE_OVERTIME,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    name: 'Approve Overtime',
    description: 'Allows approval of overtime in time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_TIME_KEEPING_RECOMPUTE_TIME,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
    name: 'Recompute Time',
    description: 'Allows recomputation of time in time keeping.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group View',
    description: 'Allows view access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_ALL,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group View All',
    description: 'Allows view all access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_BY_BRANCH,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group View By Branch',
    description:
      'Allows view by branch access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_BY_EMPLOYEE,
    type: ScopeType.BUTTON,
    parentId: ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
    name: 'Payroll Group View By Employee',
    description:
      'Allows view by employee access to the payroll group configuration.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PAGIBIG_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Pag-IBIG Configuration',
    description: 'Allows access to the Pag-IBIG configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_PHILHEALTH_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'PhilHealth Configuration',
    description: 'Allows access to the PhilHealth configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_SSS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'SSS Configuration',
    description: 'Allows access to the SSS configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_CONFIGURATION_TAX_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_CONFIGURATION' as any,
    name: 'Tax Configuration',
    description: 'Allows access to the tax configuration page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_REPORTS_SSS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_REPORTS' as any,
    name: 'SSS Contributions Report',
    description: 'Allows access to the SSS contributions report page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_REPORTS_PHILHEALTH_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_REPORTS' as any,
    name: 'PhilHealth Contributions Report',
    description: 'Allows access to the PhilHealth contributions report page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_REPORTS_PAGIBIG_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_REPORTS' as any,
    name: 'Pag-IBIG Contributions Report',
    description: 'Allows access to the Pag-IBIG contributions report page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.MANPOWER_REPORTS_TAX_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'MANPOWER_REPORTS' as any,
    name: 'Tax Withholding Report',
    description: 'Allows access to the tax withholding report page.',
    module: SystemModule.MANPOWER,
  },
  {
    id: ScopeList.PROJECT_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Project',
    description: 'Allows access to the project page.',
    module: SystemModule.PROJECT,
    aiServices: {
      availableServices: [
        'getProjectList',
        'getTaskList',
        'getProjectProgress',
        'getTaskDetails',
      ],
      aiProviders: ['gemini', 'openai'],
      contextDescription:
        'AI can access project information, task lists, and progress tracking',
    },
  },
  {
    id: 'PROJECT_DASHBOARD' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.PROJECT_ACCESS,
    name: 'Dashboard',
    description: 'Project dashboard and overview',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_MANAGEMENT' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.PROJECT_ACCESS,
    name: 'Project Management',
    description: 'Manage projects and tasks',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_LIST_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'PROJECT_MANAGEMENT' as any,
    name: 'Project List',
    description: 'View and manage project list',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_TASK_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'PROJECT_MANAGEMENT' as any,
    name: 'Task Management',
    description: 'Manage project tasks',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_TIMELINE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'PROJECT_MANAGEMENT' as any,
    name: 'Timeline',
    description: 'View project timelines and schedules',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_RESOURCES' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.PROJECT_ACCESS,
    name: 'Resources',
    description: 'Project resource management',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_TEAM_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'PROJECT_RESOURCES' as any,
    name: 'Team Management',
    description: 'Manage project teams',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_BUDGET_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'PROJECT_RESOURCES' as any,
    name: 'Budget Management',
    description: 'Manage project budgets',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_REPORTS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.PROJECT_ACCESS,
    name: 'Reports',
    description: 'Project reports and analytics',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'PROJECT_LIST_ACCESS' as any,
    name: 'Create Project',
    description: 'Allows creation of new projects',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'PROJECT_LIST_ACCESS' as any,
    name: 'Update Project',
    description: 'Allows updating project information',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: 'PROJECT_LIST_ACCESS' as any,
    name: 'Delete Project',
    description: 'Allows deletion of projects',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_TASK_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'PROJECT_TASK_ACCESS' as any,
    name: 'Create Task',
    description: 'Allows creation of new tasks',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_TASK_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'PROJECT_TASK_ACCESS' as any,
    name: 'Update Task',
    description: 'Allows updating task information',
    module: SystemModule.PROJECT,
  },
  {
    id: 'PROJECT_TASK_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: 'PROJECT_TASK_ACCESS' as any,
    name: 'Delete Task',
    description: 'Allows deletion of tasks',
    module: SystemModule.PROJECT,
  },
  {
    id: ScopeList.ASSET_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Asset',
    description: 'Allows access to the asset page.',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_WAREHOUSE' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.ASSET_ACCESS,
    name: 'Warehouse',
    description: 'Warehouse management',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_COMPANY_WAREHOUSE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_WAREHOUSE' as any,
    name: 'Company Warehouse',
    description: 'Manage company warehouse',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_PROJECT_WAREHOUSE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_WAREHOUSE' as any,
    name: 'Project Warehouse',
    description: 'Manage project warehouse',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_INTRANSIT_WAREHOUSE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_WAREHOUSE' as any,
    name: 'In Transit Warehouse',
    description: 'Manage in transit warehouse',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_TEMPORARY_WAREHOUSE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_WAREHOUSE' as any,
    name: 'Temporary Warehouse',
    description: 'Manage temporary warehouse',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_ITEM' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.ASSET_ACCESS,
    name: 'Item',
    description: 'Item management',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_ITEM_SIMPLE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_ITEM' as any,
    name: 'Simple View',
    description: 'Simple item view',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_ITEM_ADVANCE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_ITEM' as any,
    name: 'Advance View',
    description: 'Advanced item view',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_ITEM_DELETED_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_ITEM' as any,
    name: 'Deleted List',
    description: 'View deleted items',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_PURCHASING' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.ASSET_ACCESS,
    name: 'Purchasing',
    description: 'Purchasing management',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_PURCHASE_REQUEST_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_PURCHASING' as any,
    name: 'Purchase Request',
    description: 'Manage purchase requests',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_PURCHASE_ORDER_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_PURCHASING' as any,
    name: 'Purchase Order',
    description: 'Manage purchase orders',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_SUPPLIERS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_PURCHASING' as any,
    name: 'Suppliers',
    description: 'Manage suppliers',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_DELIVERIES' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.ASSET_ACCESS,
    name: 'Deliveries',
    description: 'Delivery management',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_DELIVERIES_PENDING_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_DELIVERIES' as any,
    name: 'Pending Receive',
    description: 'Manage pending receive deliveries',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_DELIVERIES_TRUCK_LOAD_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_DELIVERIES' as any,
    name: 'For Truck Load',
    description: 'Manage deliveries for truck load',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_DELIVERIES_DONE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_DELIVERIES' as any,
    name: 'Done Deliveries',
    description: 'View completed deliveries',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_DELIVERIES_CANCELED_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_DELIVERIES' as any,
    name: 'Canceled Deliveries',
    description: 'View canceled deliveries',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_EQUIPMENT' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.ASSET_ACCESS,
    name: 'Equipment',
    description: 'Equipment management',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_EQUIPMENT_LIST_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_EQUIPMENT' as any,
    name: 'Equipment List',
    description: 'View and manage equipment list',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_EQUIPMENT_PARTS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_EQUIPMENT' as any,
    name: 'Parts Maintenance',
    description: 'Manage equipment parts maintenance',
    module: SystemModule.ASSET,
  },
  {
    id: 'ASSET_EQUIPMENT_JOBORDERS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'ASSET_EQUIPMENT' as any,
    name: 'Job Orders',
    description: 'Manage equipment job orders',
    module: SystemModule.ASSET,
  },
  {
    id: ScopeList.TREASURY_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Treasury',
    description: 'Allows access to the treasury page.',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_FUND_ACCOUNT' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.TREASURY_ACCESS,
    name: 'Fund Account',
    description: 'Fund account management',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_FUND_ACCOUNT_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_FUND_ACCOUNT' as any,
    name: 'Fund Account',
    description: 'Manage fund accounts',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PAYABLES' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.TREASURY_ACCESS,
    name: 'Payables',
    description: 'Payables management',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PAYABLES_PURCHASE_ORDER_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_PAYABLES' as any,
    name: 'Purchase Order',
    description: 'Manage purchase order payments',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PAYABLES_SUPPLIERS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_PAYABLES' as any,
    name: 'Suppliers',
    description: 'Manage supplier payments',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PAYABLES_REQUEST_PAYMENT_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_PAYABLES' as any,
    name: 'Request for Payment',
    description: 'Manage payment requests',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_RECEIVABLES' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.TREASURY_ACCESS,
    name: 'Receivables',
    description: 'Receivables management',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_RECEIVABLES_PROJECT_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_RECEIVABLES' as any,
    name: 'Collection by Project',
    description: 'Manage collections by project',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_RECEIVABLES_CLIENT_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_RECEIVABLES' as any,
    name: 'Collection by Client',
    description: 'Manage collections by client',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_RECEIVABLES_LOGS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_RECEIVABLES' as any,
    name: 'Collection Logs',
    description: 'View collection logs',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_RECEIVABLES_REVIEW_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_RECEIVABLES' as any,
    name: 'For Review',
    description: 'Collections pending review',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PETTY_CASH' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.TREASURY_ACCESS,
    name: 'Petty Cash',
    description: 'Petty cash management',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PETTYCASH_HOLDERS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_PETTY_CASH' as any,
    name: 'Petty Cash Holders',
    description: 'Manage petty cash holders',
    module: SystemModule.TREASURY,
  },
  {
    id: 'TREASURY_PETTYCASH_LIQUIDATION_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'TREASURY_PETTY_CASH' as any,
    name: 'For Liquidation',
    description: 'Manage petty cash liquidation',
    module: SystemModule.TREASURY,
  },
  {
    id: ScopeList.CALENDAR_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Calendar',
    description: 'Allows access to the calendar page.',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_VIEW' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.CALENDAR_ACCESS,
    name: 'Calendar View',
    description: 'View calendar events',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_EVENTS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.CALENDAR_ACCESS,
    name: 'Events',
    description: 'Manage calendar events',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_COMPANY_EVENTS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'CALENDAR_EVENTS' as any,
    name: 'Company Events',
    description: 'Manage company-wide events',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_PERSONAL_EVENTS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'CALENDAR_EVENTS' as any,
    name: 'Personal Events',
    description: 'Manage personal events',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_SETTINGS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.CALENDAR_ACCESS,
    name: 'Settings',
    description: 'Calendar settings and preferences',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_EVENT_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'CALENDAR_COMPANY_EVENTS_ACCESS' as any,
    name: 'Create Event',
    description: 'Allows creation of new events',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_EVENT_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'CALENDAR_COMPANY_EVENTS_ACCESS' as any,
    name: 'Update Event',
    description: 'Allows updating event information',
    module: SystemModule.CALENDAR,
  },
  {
    id: 'CALENDAR_EVENT_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: 'CALENDAR_COMPANY_EVENTS_ACCESS' as any,
    name: 'Delete Event',
    description: 'Allows deletion of events',
    module: SystemModule.CALENDAR,
  },
  {
    id: ScopeList.LEADS_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Leads',
    description: 'Allows access to the leads page.',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_DASHBOARD' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.LEADS_ACCESS,
    name: 'Dashboard',
    description: 'Leads dashboard and overview',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_MANAGEMENT' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.LEADS_ACCESS,
    name: 'Lead Management',
    description: 'Manage sales leads',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_LIST_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'LEADS_MANAGEMENT' as any,
    name: 'Lead List',
    description: 'View and manage lead list',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_PIPELINE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'LEADS_MANAGEMENT' as any,
    name: 'Sales Pipeline',
    description: 'Manage sales pipeline',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_ACTIVITIES_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'LEADS_MANAGEMENT' as any,
    name: 'Activities',
    description: 'Track lead activities',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_CONFIGURATION' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.LEADS_ACCESS,
    name: 'Configuration',
    description: 'Leads module configuration',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_SOURCES_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'LEADS_CONFIGURATION' as any,
    name: 'Lead Sources',
    description: 'Manage lead sources',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_STAGES_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'LEADS_CONFIGURATION' as any,
    name: 'Pipeline Stages',
    description: 'Manage pipeline stages',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_REPORTS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.LEADS_ACCESS,
    name: 'Reports',
    description: 'Lead reports and analytics',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'LEADS_LIST_ACCESS' as any,
    name: 'Create Lead',
    description: 'Allows creation of new leads',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: 'LEADS_LIST_ACCESS' as any,
    name: 'Update Lead',
    description: 'Allows updating lead information',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: 'LEADS_LIST_ACCESS' as any,
    name: 'Delete Lead',
    description: 'Allows deletion of leads',
    module: SystemModule.LEADS,
  },
  {
    id: 'LEADS_CONVERT' as any,
    type: ScopeType.BUTTON,
    parentId: 'LEADS_LIST_ACCESS' as any,
    name: 'Convert Lead',
    description: 'Allows converting leads to customers',
    module: SystemModule.LEADS,
  },
  {
    id: ScopeList.SETTINGS_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'Settings',
    description: 'Allows access to the settings page.',
    module: SystemModule.SETTINGS,
    aiServices: {
      availableServices: [
        'getUserList',
        'getCompanyInfo',
        'getRoleList',
        'getBranchList',
      ],
      aiProviders: ['gemini', 'openai'],
      contextDescription:
        'AI can access system configuration, user management, and company settings',
    },
  },
  {
    id: 'SETTINGS_PERSONAL' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SETTINGS_ACCESS,
    name: 'Personal',
    description: 'Personal settings and preferences',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_COMPANY' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SETTINGS_ACCESS,
    name: 'Company',
    description: 'Company settings and information',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_USERS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SETTINGS_ACCESS,
    name: 'Users',
    description: 'User management and configuration',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_SECURITY' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SETTINGS_ACCESS,
    name: 'Security',
    description: 'Security and access control settings',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_WORKFLOW' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SETTINGS_ACCESS,
    name: 'Workflow',
    description: 'Workflow configuration settings',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_SYSTEM' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SETTINGS_ACCESS,
    name: 'System',
    description: 'System settings and administration',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_EMAIL_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_PERSONAL' as any,
    name: 'Email Configuration',
    description: 'Allows access to the email configuration settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_SYSTEM_EMAILS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_SYSTEM' as any,
    name: 'Sent Emails',
    description: 'Allows access to view system sent emails.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_COMPANY_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_COMPANY' as any,
    name: 'Company Information',
    description: 'Allows access to the company information settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_BRANCHES_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_COMPANY' as any,
    name: 'Branches',
    description: 'Allows access to the branches settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_USER_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_USERS' as any,
    name: 'Users',
    description: 'Allows access to the users settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_ROLE_GROUP_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_USERS' as any,
    name: 'Departments',
    description: 'Allows access to the departments (role group) settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_ROLES_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_SECURITY' as any,
    name: 'Roles',
    description: 'Allows access to the roles settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_USER_LEVEL_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_SECURITY' as any,
    name: 'User Levels',
    description: 'Allows access to the user levels settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SETTINGS_DEVELOPER_PROMOTION_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_SYSTEM' as any,
    name: 'Super Admin Promotion',
    description: 'Allows access to the super admin promotion settings.',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_WORKFLOW_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_WORKFLOW' as any,
    name: 'Purchase Request Workflow',
    description: 'Allows access to configure purchase request workflow.',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_WORKFLOW_DELIVERY_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_WORKFLOW' as any,
    name: 'Delivery Status Workflow',
    description: 'Allows access to configure delivery status workflow.',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_INACTIVE_USERS_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_USERS' as any,
    name: 'Inactive Users',
    description: 'Allows access to view and manage inactive users.',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_USER_INVITE_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_USERS' as any,
    name: 'User Invite',
    description: 'Allows access to send user invitations.',
    module: SystemModule.SETTINGS,
  },
  {
    id: 'SETTINGS_ABOUT_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'SETTINGS_SYSTEM' as any,
    name: 'About',
    description: 'View system information and version details.',
    module: SystemModule.SETTINGS,
  },
  {
    id: ScopeList.SCHOOL_MANAGEMENT_ACCESS,
    type: ScopeType.PAGE,
    parentId: null,
    name: 'School Management',
    description: 'Allows access to the school management page.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_PEOPLE_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_MANAGEMENT_ACCESS,
    name: 'People Management',
    description: 'Allows access to manage people in the school system.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_STUDENT_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_PEOPLE_MANAGEMENT_ACCESS,
    name: 'Student Management',
    description: 'Allows access to the student management page.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_GUARDIAN_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_PEOPLE_MANAGEMENT_ACCESS,
    name: 'Guardian Management',
    description: 'Allows access to the guardian management page.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_DEVICES_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_MANAGEMENT_ACCESS,
    name: 'Devices',
    description: 'Device and gate management',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_DEVICE_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: 'SCHOOL_DEVICES_ACCESS' as any,
    name: 'Device Management',
    description: 'Allows access to the device management page.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GATE_MANAGEMENT_ACCESS' as any,
    type: ScopeType.SUBPAGE,
    parentId: 'SCHOOL_DEVICES_ACCESS' as any,
    name: 'Gate Management',
    description: 'Allows access to the gate management page.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_ACADEMIC_SETUP_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_MANAGEMENT_ACCESS,
    name: 'Academic Setup',
    description: 'Allows access to the academic setup configuration.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_YEAR_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_SETUP_ACCESS,
    name: 'School Year Management',
    description: 'Allows access to manage school years and academic terms.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_GRADE_LEVEL_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_SETUP_ACCESS,
    name: 'Grade Level Management',
    description:
      'Allows access to manage grade levels from nursery to college.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_SECTION_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_SETUP_ACCESS,
    name: 'Section Management',
    description: 'Allows access to manage class sections.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_COURSE_MANAGEMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_SETUP_ACCESS,
    name: 'Course Management',
    description: 'Allows access to manage subjects and courses.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_ACADEMIC_OPERATIONS_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_MANAGEMENT_ACCESS,
    name: 'Academic Operations',
    description: 'Allows access to academic operations.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_ENROLLMENT_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_OPERATIONS_ACCESS,
    name: 'Enrollment Management',
    description: 'Allows access to manage student enrollment.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_ATTENDANCE_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_OPERATIONS_ACCESS,
    name: 'Attendance Management',
    description: 'Allows access to manage student attendance.',
    module: SystemModule.SCHOOL,
  },
  {
    id: ScopeList.SCHOOL_GRADING_ACCESS,
    type: ScopeType.SUBPAGE,
    parentId: ScopeList.SCHOOL_ACADEMIC_OPERATIONS_ACCESS,
    name: 'Grading Management',
    description: 'Allows access to manage grades and assessments.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_STUDENT_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_STUDENT_MANAGEMENT_ACCESS,
    name: 'Student Create',
    description: 'Allows creation of new students.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_STUDENT_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_STUDENT_MANAGEMENT_ACCESS,
    name: 'Student Update',
    description: 'Allows updating student information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_STUDENT_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_STUDENT_MANAGEMENT_ACCESS,
    name: 'Student Delete',
    description: 'Allows deletion of students.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GUARDIAN_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_GUARDIAN_MANAGEMENT_ACCESS,
    name: 'Guardian Create',
    description: 'Allows creation of new guardians.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GUARDIAN_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_GUARDIAN_MANAGEMENT_ACCESS,
    name: 'Guardian Update',
    description: 'Allows updating guardian information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GUARDIAN_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_GUARDIAN_MANAGEMENT_ACCESS,
    name: 'Guardian Delete',
    description: 'Allows deletion of guardians.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_DEVICE_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_DEVICE_MANAGEMENT_ACCESS,
    name: 'Device Create',
    description: 'Allows creation of new devices.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_DEVICE_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_DEVICE_MANAGEMENT_ACCESS,
    name: 'Device Update',
    description: 'Allows updating device information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_DEVICE_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_DEVICE_MANAGEMENT_ACCESS,
    name: 'Device Delete',
    description: 'Allows deletion of devices.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_YEAR_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_YEAR_MANAGEMENT_ACCESS,
    name: 'School Year Create',
    description: 'Allows creation of new school years.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_YEAR_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_YEAR_MANAGEMENT_ACCESS,
    name: 'School Year Update',
    description: 'Allows updating school year information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_YEAR_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_YEAR_MANAGEMENT_ACCESS,
    name: 'School Year Delete',
    description: 'Allows deletion of school years.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GRADE_LEVEL_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_GRADE_LEVEL_ACCESS,
    name: 'Grade Level Create',
    description: 'Allows creation of new grade levels.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GRADE_LEVEL_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_GRADE_LEVEL_ACCESS,
    name: 'Grade Level Update',
    description: 'Allows updating grade level information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_GRADE_LEVEL_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_GRADE_LEVEL_ACCESS,
    name: 'Grade Level Delete',
    description: 'Allows deletion of grade levels.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_SECTION_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_SECTION_MANAGEMENT_ACCESS,
    name: 'Section Create',
    description: 'Allows creation of new sections.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_SECTION_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_SECTION_MANAGEMENT_ACCESS,
    name: 'Section Update',
    description: 'Allows updating section information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_SECTION_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_SECTION_MANAGEMENT_ACCESS,
    name: 'Section Delete',
    description: 'Allows deletion of sections.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_COURSE_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_COURSE_MANAGEMENT_ACCESS,
    name: 'Course Create',
    description: 'Allows creation of new courses.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_COURSE_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_COURSE_MANAGEMENT_ACCESS,
    name: 'Course Update',
    description: 'Allows updating course information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_COURSE_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_COURSE_MANAGEMENT_ACCESS,
    name: 'Course Delete',
    description: 'Allows deletion of courses.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_ENROLLMENT_CREATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_ENROLLMENT_ACCESS,
    name: 'Enrollment Create',
    description: 'Allows creation of new enrollments.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_ENROLLMENT_UPDATE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_ENROLLMENT_ACCESS,
    name: 'Enrollment Update',
    description: 'Allows updating enrollment information.',
    module: SystemModule.SCHOOL,
  },
  {
    id: 'SCHOOL_ENROLLMENT_DELETE' as any,
    type: ScopeType.BUTTON,
    parentId: ScopeList.SCHOOL_ENROLLMENT_ACCESS,
    name: 'Enrollment Delete',
    description: 'Allows deletion of enrollments.',
    module: SystemModule.SCHOOL,
  },
];

export default ScopeReference;
