export default [
  {
    key: 'pieces',
    label: 'Pieces',
    abb: 'pcs',
    type: 'quantity',
  },
  {
    key: 'box',
    label: 'Box',
    abb: 'pcs',
    type: 'quantity',
  },
  {
    key: 'kilogram',
    label: 'Kilogram',
    abb: 'kg',
    type: 'weight',
  },
  {
    key: 'gram',
    label: 'Gram',
    abb: 'g',
    type: 'weight',
  },
  {
    key: 'meter',
    label: 'Meter',
    abb: 'm',
    type: 'length',
  },
  {
    key: 'centimeter',
    label: 'Centimeter',
    abb: 'cm',
    type: 'length',
  },
  {
    key: 'millimeter',
    label: 'Millimeter',
    abb: 'mm',
    type: 'length',
  },
  {
    key: 'liter',
    label: 'Liter',
    abb: 'L',
    type: 'volume',
  },
  {
    key: 'milliliter',
    label: 'Milliliter',
    abb: 'mL',
    type: 'volume',
  },
  {
    key: 'cubic_meter',
    label: 'Cubic Meter',
    abb: 'm³',
    type: 'volume',
  },
  {
    key: 'cubic_centimeter',
    label: 'Cubic Centimeter',
    abb: 'cm³',
    type: 'volume',
  },
  {
    key: 'cubic_millimeter',
    label: 'Cubic Millimeter',
    abb: 'mm³',
    type: 'volume',
  },
  {
    key: 'square_meter',
    label: 'Square Meter',
    abb: 'm²',
    type: 'area',
  },
  {
    key: 'square_centimeter',
    label: 'Square Centimeter',
    abb: 'cm²',
    type: 'area',
  },
  {
    key: 'square_millimeter',
    label: 'Square Millimeter',
    abb: 'mm²',
    type: 'area',
  },
  {
    key: 'cubic_meter_per_kilogram',
    label: 'Cubic Meter per Kilogram',
    abb: 'm³/kg',
    type: 'volume_per_weight',
  },
  {
    key: 'cubic_meter_per_gram',
    label: 'Cubic Meter per Gram',
    abb: 'm³/g',
    type: 'volume_per_weight',
  },
  {
    key: 'cubic_meter_per_liter',
    label: 'Cubic Meter per Liter',
    abb: 'm³/L',
    type: 'volume_per_volume',
  },
  {
    key: 'lot',
    label: 'Lot',
    abb: 'lot',
    type: 'quantity',
  },
  {
    key: 'set',
    label: 'Set',
    abb: 'set',
    type: 'quantity',
  },
  {
    key: 'unit',
    label: 'Unit',
    abb: 'unit',
    type: 'quantity',
  },
  {
    key: 'lump_sum',
    label: 'Lump Sum',
    abb: 'lump sum',
    type: 'quantity',
  },
  {
    key: 'kilometer',
    label: 'Kilometer',
    abb: 'km',
    type: 'length',
  },
  {
    key: 'foot',
    label: 'Foot',
    abb: 'ft',
    type: 'length',
  },
  {
    key: 'inch',
    label: 'Inch',
    abb: 'in',
    type: 'length',
  },
  {
    key: 'linear_meter',
    label: 'Linear Meter',
    abb: 'lin.m',
    type: 'length',
  },
  {
    key: 'running_meter',
    label: 'Running Meter',
    abb: 'rm',
    type: 'length',
  },
  {
    key: 'square_kilometer',
    label: 'Square Kilometer',
    abb: 'sqkm',
    type: 'area',
  },
  {
    key: 'square_inch',
    label: 'Square Inch',
    abb: 'sqin',
    type: 'area',
  },
  {
    key: 'square_foot',
    label: 'Square Foot',
    abb: 'sqft',
    type: 'area',
  },
  {
    key: 'hectare',
    label: 'Hectare',
    abb: 'ha',
    type: 'area',
  },
  {
    key: 'cubic_foot',
    label: 'Cubic Foot',
    abb: 'cuft',
    type: 'volume',
  },
  {
    key: 'cubic_inch',
    label: 'Cubic Inch',
    abb: 'cuin',
    type: 'volume',
  },
  {
    key: 'cubic_yard',
    label: 'Cubic Yard',
    abb: 'cuyd',
    type: 'volume',
  },
  {
    key: 'gallon',
    label: 'Gallon',
    abb: 'gal',
    type: 'volume',
  },
  {
    key: 'barrel_liquid',
    label: 'Barrel (liquid)',
    abb: 'bbl',
    type: 'volume',
  },
  {
    key: 'milligram',
    label: 'Milligram',
    abb: 'mg',
    type: 'weight',
  },
  {
    key: 'pound',
    label: 'Pound',
    abb: 'lb',
    type: 'weight',
  },
  {
    key: 'metric_ton',
    label: 'Metric Ton',
    abb: 'ton / MT',
    type: 'weight',
  },
  {
    key: 'ounce',
    label: 'Ounce',
    abb: 'oz',
    type: 'weight',
  },
  {
    key: 'hour',
    label: 'Hour',
    abb: 'hr',
    type: 'time',
  },
  {
    key: 'day',
    label: 'Day',
    abb: 'day',
    type: 'time',
  },
  {
    key: 'week',
    label: 'Week',
    abb: 'wk',
    type: 'time',
  },
  {
    key: 'month',
    label: 'Month',
    abb: 'mo',
    type: 'time',
  },
  {
    key: 'work_shift',
    label: 'Work Shift',
    abb: 'shift',
    type: 'time',
  },
  {
    key: 'manday',
    label: 'Man-Day',
    abb: 'manday',
    type: 'time',
  },
  {
    key: 'mandays',
    label: 'Man-Days',
    abb: 'mandays',
    type: 'time',
  },
  {
    key: 'bag_cement_etc',
    label: 'Bag (cement, etc.)',
    abb: 'bag',
    type: 'material',
  },
  {
    key: 'sack',
    label: 'Sack',
    abb: 'sack',
    type: 'material',
  },
  {
    key: 'drum',
    label: 'Drum',
    abb: 'drum',
    type: 'material',
  },
  {
    key: 'roll',
    label: 'Roll',
    abb: 'roll',
    type: 'material',
  },
  {
    key: 'can_paint_chemicals',
    label: 'Can (paint, chemicals)',
    abb: 'can',
    type: 'material',
  },
  {
    key: 'tin',
    label: 'Tin',
    abb: 'tin',
    type: 'material',
  },
  {
    key: 'sheet',
    label: 'Sheet',
    abb: 'sheet',
    type: 'material',
  },
  {
    key: 'board',
    label: 'Board',
    abb: 'board',
    type: 'material',
  },
  {
    key: 'panel',
    label: 'Panel',
    abb: 'panel',
    type: 'material',
  },
  {
    key: 'bottle',
    label: 'Bottle',
    abb: 'bottle',
    type: 'material',
  },
  {
    key: 'tube',
    label: 'Tube',
    abb: 'tube',
    type: 'material',
  },
  {
    key: 'bundle',
    label: 'Bundle',
    abb: 'bundle',
    type: 'material',
  },
  {
    key: 'length',
    label: 'Length',
    abb: 'length',
    type: 'material',
  },
];
