import { ScopeList } from '@prisma/client';
import { SystemModule } from '../shared/enums/user-level.enums';
import { UserLevelDataResponse } from '../shared/response/user-level.response';

const UserLevelReference: UserLevelDataResponse[] = [
  {
    id: 0,
    label: 'HR Admin',
    systemModule: SystemModule.MANPOWER,
    scope: [
      ScopeList.MANPOWER_ACCESS,
      ScopeList.MANPOWER_HRIS_ACCESS,
      ScopeList.MANPOWER_HRIS_CREATE,
      ScopeList.MANPOWER_HRIS_UPDATE,
      ScopeList.MANPOWER_HRIS_DELETE,
      ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
      ScopeList.MANPOWER_PAYROLL_SUBMIT_FOR_REVIEW,
      ScopeList.MANPOWER_PAYROLL_PROCESS_FOR_REVIEW,
      ScopeList.MANPOWER_PAYROLL_SUBMIT_POSTING,
      ScopeList.MANPOWER_CONFIGURATION_ALLOWANCE_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_DEDUCTION_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_CREATE,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_UPDATE,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_DELETE,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_ALL,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_BY_BRANCH,
      ScopeList.MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_BY_EMPLOYEE,
      ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_CREATE,
      ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_UPDATE,
      ScopeList.MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_DELETE,
      ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_CREATE,
      ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_UPDATE,
      ScopeList.MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_DELETE,
      ScopeList.MANPOWER_CONFIGURATION_PAGIBIG_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_PHILHEALTH_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_SCHEDULE_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_SHIFT_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_SSS_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_TAX_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_CUTOFF_ACCESS,
      ScopeList.MANPOWER_CONFIGURATION_CUTOFF_CREATE,
      ScopeList.MANPOWER_CONFIGURATION_CUTOFF_UPDATE,
      ScopeList.MANPOWER_CONFIGURATION_CUTOFF_DELETE,
      ScopeList.MANPOWER_REPORTS_SSS_ACCESS,
      ScopeList.MANPOWER_REPORTS_PHILHEALTH_ACCESS,
      ScopeList.MANPOWER_REPORTS_PAGIBIG_ACCESS,
      ScopeList.MANPOWER_REPORTS_TAX_ACCESS,
    ],
  },
  {
    id: 0,
    label: 'HR Manager',
    systemModule: SystemModule.MANPOWER,
    scope: [
      ScopeList.MANPOWER_ACCESS,
      ScopeList.MANPOWER_HRIS_ACCESS,
      ScopeList.MANPOWER_HRIS_CREATE,
      ScopeList.MANPOWER_HRIS_UPDATE,
      ScopeList.MANPOWER_HRIS_DELETE,
      ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
      ScopeList.MANPOWER_PAYROLL_SUBMIT_FOR_REVIEW,
    ],
  },
  {
    id: 0,
    label: 'HR Guest',
    systemModule: SystemModule.MANPOWER,
    scope: [
      ScopeList.MANPOWER_ACCESS,
      ScopeList.MANPOWER_HRIS_ACCESS,
      ScopeList.MANPOWER_PAYROLL_CENTER_ACCESS,
    ],
  },
  {
    id: 0,
    label: 'Timekeeper (All Branch)',
    systemModule: SystemModule.MANPOWER,
    scope: [
      ScopeList.MANPOWER_TIME_KEEPING_ACCESS_ALL,
      ScopeList.MANPOWER_TIME_KEEPING_CREATE_RAW_LOGS,
      ScopeList.MANPOWER_TIME_KEEPING_EDIT_TIME,
      ScopeList.MANPOWER_TIME_KEEPING_APPROVE_REST_DAY,
      ScopeList.MANPOWER_TIME_KEEPING_APPROVE_OVERTIME,
    ],
  },
  {
    id: 0,
    label: 'Timekeeper (By Branch)',
    systemModule: SystemModule.MANPOWER,
    scope: [
      ScopeList.MANPOWER_TIME_KEEPING_ACCESS_BY_BRANCH,
      ScopeList.MANPOWER_TIME_KEEPING_CREATE_RAW_LOGS,
      ScopeList.MANPOWER_TIME_KEEPING_EDIT_TIME,
      ScopeList.MANPOWER_TIME_KEEPING_APPROVE_REST_DAY,
      ScopeList.MANPOWER_TIME_KEEPING_APPROVE_OVERTIME,
    ],
  },
  {
    id: 0,
    label: 'Asset Admin',
    systemModule: SystemModule.ASSET,
    scope: [ScopeList.ASSET_ACCESS],
  },
  {
    id: 0,
    label: 'Asset Manager',
    systemModule: SystemModule.ASSET,
    scope: [ScopeList.ASSET_ACCESS],
  },
  {
    id: 0,
    label: 'Asset Guest',
    systemModule: SystemModule.ASSET,
    scope: [ScopeList.ASSET_ACCESS],
  },
  {
    id: 0,
    label: 'Project Admin',
    systemModule: SystemModule.PROJECT,
    scope: [ScopeList.PROJECT_ACCESS],
  },
  {
    id: 0,
    label: 'Project Manager',
    systemModule: SystemModule.PROJECT,
    scope: [ScopeList.PROJECT_ACCESS],
  },
  {
    id: 0,
    label: 'Project Guest',
    systemModule: SystemModule.PROJECT,
    scope: [ScopeList.PROJECT_ACCESS],
  },
  {
    id: 0,
    label: 'Treasury Admin',
    systemModule: SystemModule.TREASURY,
    scope: [ScopeList.TREASURY_ACCESS],
  },
  {
    id: 0,
    label: 'Treasury Manager',
    systemModule: SystemModule.TREASURY,
    scope: [ScopeList.TREASURY_ACCESS],
  },
  {
    id: 0,
    label: 'Treasury Guest',
    systemModule: SystemModule.TREASURY,
    scope: [ScopeList.TREASURY_ACCESS],
  },
  {
    id: 0,
    label: 'Calendar User',
    systemModule: SystemModule.CALENDAR,
    scope: [ScopeList.CALENDAR_ACCESS],
  },
  {
    id: 0,
    label: 'Calendar Admin',
    systemModule: SystemModule.CALENDAR,
    scope: [ScopeList.CALENDAR_ACCESS],
  },
  {
    id: 0,
    label: 'Leads Admin',
    systemModule: SystemModule.LEADS,
    scope: [ScopeList.LEADS_ACCESS],
  },
  {
    id: 0,
    label: 'Leads Manager',
    systemModule: SystemModule.LEADS,
    scope: [ScopeList.LEADS_ACCESS],
  },
  {
    id: 0,
    label: 'Settings Admin',
    systemModule: SystemModule.SETTINGS,
    scope: [ScopeList.SETTINGS_ACCESS],
  },
  {
    id: 0,
    label: 'Settings Manager',
    systemModule: SystemModule.SETTINGS,
    scope: [ScopeList.SETTINGS_ACCESS],
  },
  {
    id: 0,
    label: 'Settings Guest',
    systemModule: SystemModule.SETTINGS,
    scope: [ScopeList.SETTINGS_ACCESS],
  },
];

export default UserLevelReference;
