-- AlterTable
ALTER TABLE "EmployeeTimekeepingLogs" ALTER COLUMN "timeIn" SET DEFAULT '00:00',
ALTER COLUMN "timeIn" SET DATA TYPE TEXT,
ALTER COLUMN "timeOut" SET DEFAULT '00:00',
ALTER COLUMN "timeOut" SET DATA TYPE TEXT;
