/*
  Warnings:

  - The values [FEATURE,ACTION] on the enum `ScopeType` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "UserLevel" AS ENUM ('DASHBOARD_USER', 'DASHBOARD_ADMIN', 'MANPOWER_ADMIN', 'MANPOWER_MANAGER', 'MANPOWER_GUEST', 'TIMEKEEPER_ALL_BRANCH', 'TIMEKEEPER_BY_BRANCH', 'ASSET_ADMIN', 'ASSET_MANAGER', 'ASSET_GUEST', 'PROJECT_ADMIN', 'PROJECT_MANAGER', 'PROJECT_GUEST', 'TREASURY_ADMIN', 'TREASURY_MANAGER', 'TREASURY_GUEST', 'CALENDAR_ADMIN', 'CALENDAR_USER', 'LEADS_ADMIN', 'LEADS_MANAGER', 'LEADS_GUEST', 'SETTINGS_ADMIN', 'SETTINGS_MANAGER', 'SETTINGS_GUEST');

-- CreateEnum
CREATE TYPE "SystemModule" AS ENUM ('PROJECT', 'MANPOWER', 'TREASURY', 'CALENDAR', 'LEADS', 'SETTINGS', 'ASSET');

-- CreateEnum
CREATE TYPE "ScopeList" AS ENUM ('DASHBOARD_TASK_WIDGET', 'DASHBOARD_UPDATE_WIDGET', 'DASHBOARD_PAYROLL_FILING_WIDGET', 'MANPOWER_ACCESS', 'MANPOWER_HRIS_ACCESS', 'MANPOWER_HRIS_CREATE', 'MANPOWER_HRIS_UPDATE', 'MANPOWER_HRIS_DELETE', 'MANPOWER_PAYROLL_CENTER_ACCESS', 'MANPOWER_PAYROLL_SUBMIT_FOR_REVIEW', 'MANPOWER_PAYROLL_PROCESS_FOR_REVIEW', 'MANPOWER_PAYROLL_SUBMIT_POSTING', 'MANPOWER_PAYSLIP_CENTER', 'MANPOWER_TEAM_ATTENDANCE_ACCESS', 'MANPOWER_CONFIGURATION_SERVICE_INCLUSIVE_LEAVE_ACCESS', 'MANPOWER_TEAM_SHIFTS_ACCESS', 'MANPOWER_TIME_KEEPING_ACCESS_ALL', 'MANPOWER_TIME_KEEPING_ACCESS_BY_BRANCH', 'MANPOWER_TIME_KEEPING_CREATE_RAW_LOGS', 'MANPOWER_TIME_KEEPING_DELETE_RAW_LOGS', 'MANPOWER_TIME_KEEPING_EDIT_TIME', 'MANPOWER_TIME_KEEPING_APPROVE_REST_DAY', 'MANPOWER_TIME_KEEPING_APPROVE_OVERTIME', 'MANPOWER_TIME_KEEPING_RECOMPUTE_TIME', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_ACCESS', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_CREATE', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_UPDATE', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_DELETE', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_ALL', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_BY_BRANCH', 'MANPOWER_CONFIGURATION_PAYROLL_GROUP_VIEW_BY_EMPLOYEE', 'MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_ACCESS', 'MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_CREATE', 'MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_UPDATE', 'MANPOWER_CONFIGURATION_LOCAL_HOLIDAY_DELETE', 'MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_ACCESS', 'MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_CREATE', 'MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_UPDATE', 'MANPOWER_CONFIGURATION_NATIONAL_HOLIDAY_DELETE', 'MANPOWER_CONFIGURATION_PAGIBIG_ACCESS', 'MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_ACCESS', 'MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_CREATE', 'MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_UPDATE', 'MANPOWER_CONFIGURATION_PAYROLL_APPROVERS_DELETE', 'MANPOWER_CONFIGURATION_PHILHEALTH_ACCESS', 'MANPOWER_CONFIGURATION_SCHEDULE_ACCESS', 'MANPOWER_CONFIGURATION_SCHEDULE_CREATE', 'MANPOWER_CONFIGURATION_SCHEDULE_UPDATE', 'MANPOWER_CONFIGURATION_SCHEDULE_DELETE', 'MANPOWER_CONFIGURATION_SHIFT_ACCESS', 'MANPOWER_CONFIGURATION_SHIFT_CREATE', 'MANPOWER_CONFIGURATION_SHIFT_UPDATE', 'MANPOWER_CONFIGURATION_SHIFT_DELETE', 'MANPOWER_CONFIGURATION_SSS_ACCESS', 'MANPOWER_CONFIGURATION_TAX_ACCESS', 'MANPOWER_CONFIGURATION_DEDUCTION_ACCESS', 'MANPOWER_CONFIGURATION_DEDUCTION_CREATE', 'MANPOWER_CONFIGURATION_DEDUCTION_UPDATE', 'MANPOWER_CONFIGURATION_DEDUCTION_DELETE', 'MANPOWER_CONFIGURATION_ALLOWANCE_ACCESS', 'MANPOWER_CONFIGURATION_ALLOWANCE_CREATE', 'MANPOWER_CONFIGURATION_ALLOWANCE_UPDATE', 'MANPOWER_CONFIGURATION_ALLOWANCE_DELETE', 'MANPOWER_CONFIGURATION_CUTOFF_ACCESS', 'MANPOWER_CONFIGURATION_CUTOFF_CREATE', 'MANPOWER_CONFIGURATION_CUTOFF_UPDATE', 'MANPOWER_CONFIGURATION_CUTOFF_DELETE', 'MANPOWER_TIME_KEEPING_DEVICE_ACCESS', 'PROJECT_ACCESS', 'ASSET_ACCESS', 'TREASURY_ACCESS', 'CALENDAR_ACCESS', 'LEADS_ACCESS', 'SETTINGS_ACCESS');

-- AlterEnum
BEGIN;
CREATE TYPE "ScopeType_new" AS ENUM ('PAGE', 'SUBPAGE', 'BUTTON', 'WIDGET');
ALTER TYPE "ScopeType" RENAME TO "ScopeType_old";
ALTER TYPE "ScopeType_new" RENAME TO "ScopeType";
DROP TYPE "ScopeType_old";
COMMIT;

-- CreateTable
CREATE TABLE "UserLevelModel" (
    "id" "UserLevel" NOT NULL,
    "label" TEXT NOT NULL,
    "systemModule" "SystemModule" NOT NULL,
    "companyId" INTEGER NOT NULL,
    "scope" "ScopeList"[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserLevelModel_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "UserLevelModel" ADD CONSTRAINT "UserLevelModel_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
