-- CreateEnum
CREATE TYPE "BusinessType" AS ENUM ('SOLE_PROPRIETORSHIP', 'PARTNERSHIP', 'CORPORATION', 'OTHERS');

-- CreateEnum
CREATE TYPE "Industry" AS ENUM ('CONSTRUCTION', 'MANUFACTURING', 'RETAIL', 'SERVICES', 'OTHERS');

-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "businessType" "BusinessType" NOT NULL DEFAULT 'OTHERS',
ADD COLUMN     "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "industry" "Industry" NOT NULL DEFAULT 'OTHERS',
ADD COLUMN     "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "registrationNo" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tinNo" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "website" TEXT NOT NULL DEFAULT '';
