export default {
  defaultOrderBy: 'studentNumber',
  defaultOrderType: 'asc',
  search: [
    {
      key: 'firstName',
      label: 'Search by First Name',
      column: 'firstName',
    },
    {
      key: 'lastName',
      label: 'Search by Last Name',
      column: 'lastName',
    },
    {
      key: 'studentNumber',
      label: 'Search by Student Number',
      column: 'studentNumber',
    },
    {
      key: 'lrn',
      label: 'Search by LRN',
      column: 'lrn',
    },
  ],
  filters: [
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ],
    },
  ],
  columns: [
    {
      key: 'profilePhoto',
      label: 'Photo',
      class: 'text-center',
      field: 'profilePhoto',
      sortable: false,
      slot: 'profilePhoto',
    },
    {
      key: 'studentNumber',
      label: 'Student No.',
      class: 'text-left',
      field: 'studentNumber',
      sortable: true,
    },
    {
      key: 'firstName',
      label: 'Student Name',
      class: 'text-left',
      field: 'firstName',
      sortable: true,
      slot: 'studentName',
    },
    {
      key: 'section',
      label: 'Grade Level / Section',
      class: 'text-center',
      field: 'section',
      sortable: false,
      slot: 'section',
    },
    {
      key: 'guardianName',
      label: 'Guardian Name',
      class: 'text-left',
      field: 'guardian.name',
      sortable: false,
      slot: 'guardianName',
    },
    {
      key: 'guardianAddress',
      label: 'Address',
      class: 'text-left',
      field: 'guardian.address',
      sortable: false,
      slot: 'guardianAddress',
    },
    {
      key: 'guardianContact',
      label: 'Contact No.',
      class: 'text-left',
      field: 'guardian.contactNumber',
      sortable: false,
      slot: 'guardianContact',
    },
    {
      key: 'createdAt',
      label: 'Date Created',
      class: 'text-center',
      field: 'createdAt',
      sortable: true,
      slot: 'createdAt',
    },
  ],
  exportHeaders: [
    'studentNumber',
    'firstName',
    'lastName',
    'middleName',
    'dateOfBirth',
    'gender',
    'location.name',
    'lrn',
    'createdAt',
    'isActive',
  ],
};