<template>
  <div class="q-pa-md example-column-vertical-alignment" @keydown.f9="fillData">
    <div class="column justify-start">
      <!-- Item name and SKU -->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="text" label="Item Name" class="text-body-small" v-model="form.itemName"></GInput>
        </div>
        <div class="col">
          <GInput required :type="itemInformation ? 'text' : 'text_checkbox'" label="SKU" class="text-body-small" v-model="form.sku"
            checkboxLabel="Auto Generated SKU" :enabledCheckbox="form.isAutoGeneratedSku"
            @isCheckboxTicked="onCheckboxTicked"></GInput>
        </div>
      </div>
      <!-- Description -->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="textarea" label="Description" class="text-body-small" v-model="form.description"></GInput>
        </div>
      </div>
      <!-- Estimated buying price & Unit Size-->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="text" label="Estimated Buying Price" class="text-body-small" v-model="form.estimatedBuyingPrice"></GInput>
        </div>
        <!-- Tags -->
        <div class="col">
          <GInput required type="number" label="Size" class="text-body-small" v-model="form.size"></GInput>
        </div>
        <div v-if="showUom" class="col">
          <GInput required type="select" apiUrl="select-box/unit-of-measurement-list" label="Unit of Measurement"
            class="text-body-small" v-model="form.uom"></GInput>
        </div>
      </div>
      <!-- Selling Price & Stock Levels -->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="text" label="Selling Price" v-model="form.sellingPrice"></GInput>
        </div>
        <div class="col">
          <GInput required type="number" label="Minimum Stock Level" v-model="form.minimumStockLevel"></GInput>
        </div>
        <div class="col">
          <GInput required type="number" label="Maximum Stock Level" v-model="form.maximumStockLevel"></GInput>
        </div>
      </div>
      <!-- Tags -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col">
          <tags-partial ref="tagsPartial" class="text-body-small" v-model="isTagPartialDisplayed" @onTagUpdate="onTagUpdated" />
        </div>
      </div>
      <!-- Category & Branch -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col">
          <q-select
            v-model="form.categoryId"
            :options="categoryOptions"
            option-label="name"
            option-value="id"
            label="Category"
            clearable
            emit-value
            map-options
            outlined
            dense
            class="text-body-small"
            :loading="loadingCategories"
          />
        </div>
        <div class="col">
          <q-select
            v-model="form.branchId"
            :options="branchOptions"
            option-label="name"
            option-value="id"
            label="Branch"
            clearable
            emit-value
            map-options
            outlined
            dense
            class="text-body-small"
            :loading="loadingBranches"
          />
        </div>
      </div>
      <!-- Brand -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col">
          <GInput
            ref="brandSelect"
            v-model="form.brandId"
            type="select-search-with-add"
            apiUrl="brand/select-box"
            label="Brand"
            nullOption="No Brand"
            class="text-body-small"
            @showAddDialog="showBrandAddDialog"
          />
        </div>
      </div>
      <!-- Keywords -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col">
          <keywords-partial ref="keywordsPartial" class="text-body-small" v-model="isKeywordsPartialDisplayed" @onKeywordUpdate="onKeywordUpdated" />
        </div>
      </div>
      <!-- Enable in POS -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col flex items-center">
          <q-checkbox v-model="form.enabledInPOS" label="Enable in POS" class="text-body-small" />
        </div>
      </div>
    </div>

    <!-- Add Brand Dialog -->
    <AddEditBrandDialog
      v-if="isAddBrandDialogOpen"
      v-model="isAddBrandDialogOpen"
      @saveDone="selectNewBrand"
    />
  </div>
</template>
<script>
import { defineAsyncComponent } from 'vue';
import GInput from "../../../../components/shared/form/GInput.vue";
import TagsPartial from '../Partials/TagsPartial.vue';
import KeywordsPartial from '../Partials/KeywordsPartial.vue';
import { environment } from 'src/boot/axios';

// Lazy-loaded dialog (ALL dialogs must be lazy loaded - CLAUDE.md)
const AddEditBrandDialog = defineAsyncComponent(() =>
  import('../../../dialog/AddEditBrandDialog.vue')
);

export default {
  name: 'SimpleItem',
  components: {
    GInput,
    TagsPartial,
    KeywordsPartial,
    AddEditBrandDialog,
  },
  props: {
    itemInformation: {
      type: Object || null,
      required: false,
    },
  },
  data: () => ({
    isTagHidden: false,
    showUom: false,
    form: {
      itemName: '',
      sku: '',
      isAutoGeneratedSku: true,
      description: '',
      estimatedBuyingPrice: '',
      size: 0,
      unit: '',
      tags: [],
      uom: '',
      sellingPrice: '',
      minimumStockLevel: 0,
      maximumStockLevel: 0,
      categoryId: null,
      keywords: [],
      enabledInPOS: false,
      branchId: null,
      brandId: null,
    },
    isTagPartialDisplayed: true,
    isKeywordsPartialDisplayed: true,
    isAddBrandDialogOpen: false,
    categoryOptions: [],
    branchOptions: [],
    loadingCategories: false,
    loadingBranches: false,
  }),
  watch: {
    form: {
      handler(value) {
        this.$emit('onFormUpdate', {
          type: 'simple',
          data: value,
        });
      },
      deep: true,
    },
    'form.itemName': {
      handler(value) {
        if (this.form.isAutoGeneratedSku) {
          this.form.sku = this.formatCode(value);
        }
      },
    },
  },
  mounted() {
    this.isTagHidden = false;
    this.fetchCategoryOptions();
    this.fetchBranchOptions();
    this.initialize()
  },
  computed: {},
  methods: {
    async fetchCategoryOptions() {
      this.loadingCategories = true;
      try {
        const response = await this.$api.get('/item-category/select-box');
        this.categoryOptions = response.data;
      } catch (error) {
        console.error('Error fetching categories:', error);
      } finally {
        this.loadingCategories = false;
      }
    },
    async fetchBranchOptions() {
      this.loadingBranches = true;
      try {
        const response = await this.$api.get('/branch/select-box');
        this.branchOptions = response.data;
      } catch (error) {
        console.error('Error fetching branches:', error);
      } finally {
        this.loadingBranches = false;
      }
    },
    async initialize() {
      if (this.itemInformation) {
        this.form.itemName = this.itemInformation.name;
        this.form.sku = this.itemInformation.sku;
        this.form.description = this.itemInformation.description;

        if (this.itemInformation.hasOwnProperty('formattedEstimatedBuyingPrice')) {
          this.form.estimatedBuyingPrice = this.itemInformation.formattedEstimatedBuyingPrice.raw;
        }
        else {
          this.form.estimatedBuyingPrice = this.itemInformation.estimatedBuyingPrice.raw;
        }

        this.form.size = this.itemInformation.rawSize || 0;
        this.form.unit = this.itemInformation.unit;
        this.form.isAutoGeneratedSku = false;
        this.form.tags = this.itemInformation.tags;
        this.form.uom = this.itemInformation.uom;
        
        // Handle sellingPrice consistently with estimatedBuyingPrice
        if (this.itemInformation.sellingPrice && typeof this.itemInformation.sellingPrice === 'object' && this.itemInformation.sellingPrice.hasOwnProperty('raw')) {
          this.form.sellingPrice = this.itemInformation.sellingPrice.raw;
        } else {
          this.form.sellingPrice = this.itemInformation.sellingPrice || '';
        }
        
        // Handle minimumStockLevel
        if (this.itemInformation.minimumStockLevel && typeof this.itemInformation.minimumStockLevel === 'object' && this.itemInformation.minimumStockLevel.hasOwnProperty('raw')) {
          this.form.minimumStockLevel = this.itemInformation.minimumStockLevel.raw;
        } else {
          this.form.minimumStockLevel = this.itemInformation.minimumStockLevel || 0;
        }
        
        // Handle maximumStockLevel
        if (this.itemInformation.maximumStockLevel && typeof this.itemInformation.maximumStockLevel === 'object' && this.itemInformation.maximumStockLevel.hasOwnProperty('raw')) {
          this.form.maximumStockLevel = this.itemInformation.maximumStockLevel.raw;
        } else {
          this.form.maximumStockLevel = this.itemInformation.maximumStockLevel || 0;
        }

        this.$refs.tagsPartial.tags = this.itemInformation.tags;
        this.$refs.keywordsPartial.keywords = this.itemInformation.keywords || [];

        // Handle new fields
        this.form.categoryId = this.itemInformation.categoryId || null;
        this.form.brandId = this.itemInformation.brandId || null;
        this.form.enabledInPOS = this.itemInformation.enabledInPOS || false;
        this.form.branchId = this.itemInformation.branchId || null;

        // Set brand after refs are ready
        await this.$nextTick();
        if (this.form.brandId && this.$refs.brandSelect) {
          await this.$refs.brandSelect.setAutoSelect(this.form.brandId);
        }

        if (this.itemInformation.hasOwnProperty('parent') && this.itemInformation.parent) {
          this.isTagHidden = true;
        }
        else {
          this.showUom = true
        }
      }
      else {
        this.showUom = true
      }
    },
    onCheckboxTicked(val) {
      this.form.isAutoGeneratedSku = val;

      if (!val) {
        this.form.sku = '';
      }
    },
    onTagUpdated(val) {
      this.form.tags = val;
    },
    onKeywordUpdated(val) {
      this.form.keywords = val;
    },
    fillData() {
      if (environment === 'development') {
        const randomNumber = Math.floor(Math.random() * 1000);
        const itemName = `Item-${randomNumber}`;

        this.form = {
          ...this.form,
          itemName: itemName,
          sku: itemName,
          description: `Random Description ${randomNumber}`,
          estimatedBuyingPrice: randomNumber,
          size: randomNumber,
          sellingPrice: randomNumber * 1.5,
          minimumStockLevel: 10,
          maximumStockLevel: 100,
        };

        this.$q.notify({
          color: 'grey-8',
          message: 'Data filled successfully',
          position: 'top',
        });
      }
    },
    showBrandAddDialog() {
      this.isAddBrandDialogOpen = true;
    },
    async selectNewBrand(data) {
      const autoSelect = data.id;
      await this.$refs.brandSelect.refreshSelectOptions(autoSelect);
      this.form.brandId = autoSelect;
    },
  },
};
</script>
