<template>
  <div class="example-column-vertical-alignment q-pa-md" @keydown.f9="fillData">
    <div class="column justify-start">
      <!-- Type (only shown during creation) -->
      <div class="col q-mb-md">
        <div class="label">Type</div>
        <q-select v-model="form.itemType" :options="typeOptions" outlined dense class="text-body-small" emit-value
          map-options />
      </div>
      <!-- Item name and SKU -->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="text" label="Item Name" class="text-body-small" v-model="form.itemName"></GInput>
        </div>
        <div class="col">
          <GInput required :type="itemInformation ? 'text' : 'text_checkbox'" label="SKU" class="text-body-small"
            v-model="form.sku" checkboxLabel="Auto Generated SKU" :enabledCheckbox="form.isAutoGeneratedSku"
            @isCheckboxTicked="onCheckboxTicked"></GInput>
        </div>
      </div>
      <!-- Description -->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="textarea" label="Description" class="text-body-small" v-model="form.description">
          </GInput>
        </div>
      </div>
      <!-- Estimated buying price & Unit Size-->
      <div v-if="form.itemType !== 'ITEM_GROUP'" class="row q-gutter-sm">
        <div class="col">
          <GInput required type="text" label="Estimated Buying Price" class="text-body-small"
            v-model="form.estimatedBuyingPrice"></GInput>
        </div>
        <!-- Tags -->
        <div class="col">
          <GInput required type="number" label="Size" class="text-body-small" v-model="form.size"></GInput>
        </div>
        <div v-if="showUom" class="col">
          <GInput required type="select" apiUrl="select-box/unit-of-measurement-list" label="Unit of Measurement"
            class="text-body-small" v-model="form.uom"></GInput>
        </div>
      </div>
      <!-- Selling Price & Stock Levels -->
      <div class="row q-gutter-sm">
        <div class="col">
          <GInput required type="number" label="Selling Price" v-model="form.sellingPrice"></GInput>
        </div>
        <div v-if="form.itemType !== 'ITEM_GROUP'" class="col">
          <GInput required type="number" label="Minimum Stock Level" v-model="form.minimumStockLevel"></GInput>
        </div>
        <div v-if="form.itemType !== 'ITEM_GROUP'" class="col">
          <GInput required type="number" label="Maximum Stock Level" v-model="form.maximumStockLevel"></GInput>
        </div>
      </div>
      <!-- Tags -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col">
          <tags-partial ref="tagsPartial" class="text-body-small" v-model="isTagPartialDisplayed"
            @onTagUpdate="onTagUpdated" />
        </div>
      </div>
      <!-- Category & Branch -->
      <div v-if="!isTagHidden" class="row q-gutter-sm q-pb-md">
        <div class="col">
          <div class="label">Category</div>
          <q-select v-model="form.categoryId" :options="categoryOptions" option-label="name" option-value="id" clearable
            emit-value map-options outlined dense class="text-body-small" :loading="loadingCategories" />
        </div>
        <div class="col">
          <div class="label">Branch</div>
          <q-select v-model="form.branchId" :options="branchOptions" option-label="name" option-value="id" clearable
            emit-value map-options outlined dense class="text-body-small" :loading="loadingBranches" />
        </div>
      </div>
      <!-- Brand -->
      <div v-if="!isTagHidden" class="row q-gutter-sm q-mb-md">
        <div class="col">
          <GInput ref="brandSelect" v-model="form.brandId" type="select-search-with-add" apiUrl="brand/select-box"
            label="Brand" nullOption="No Brand" class="text-body-small" @showAddDialog="showBrandAddDialog" />
        </div>
      </div>
      <!-- Keywords -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col">
          <keywords-partial ref="keywordsPartial" class="text-body-small" v-model="isKeywordsPartialDisplayed"
            @onKeywordUpdate="onKeywordUpdated" />
        </div>
      </div>
      <!-- Enable in POS -->
      <div v-if="!isTagHidden" class="row q-gutter-sm">
        <div class="col flex items-center">
          <q-checkbox v-model="form.enabledInPOS" label="Enable in POS" class="text-body-small" />
        </div>
      </div>

      <!-- Item Group Items (shown when Type = Item Group, in both create and edit mode) -->
      <div v-if="form.itemType === 'ITEM_GROUP'" class="row q-gutter-sm">
        <div class="col">
          <div class="text-body-medium q-mb-sm">Group Items</div>
          <q-card flat bordered>
            <q-card-section>
              <div v-if="form.groupItems.length === 0" class="text-center text-grey q-pa-md">
                No items added to this group
              </div>
              <q-list v-else separator>
                <q-item v-for="(item, index) in form.groupItems" :key="item.id">
                  <q-item-section>
                    <q-item-label>{{ item.name }}</q-item-label>
                    <q-item-label caption>{{ item.sku }}</q-item-label>
                  </q-item-section>
                  <q-item-section side style="min-width: 100px">
                    <q-input v-model.number="item.quantity" type="number" label="Qty" outlined dense :min="1"
                      class="text-body-small" />
                  </q-item-section>
                  <q-item-section side>
                    <GButton
                      variant="icon"
                      icon="close"
                      color="red"
                      @click="removeGroupItem(index)"
                      tooltip="Remove item"
                    />
                  </q-item-section>
                </q-item>
              </q-list>
              <div class="q-mt-md">
                <GButton
                  label="Add Items"
                  icon="add"
                  variant="outline"
                  color="primary"
                  @click="isChooseItemDialogOpen = true"
                  block
                />
              </div>
            </q-card-section>
          </q-card>
        </div>
      </div>
    </div>

    <!-- Choose Item Dialog -->
    <ChooseItemDialog v-if="isChooseItemDialogOpen" v-model="isChooseItemDialogOpen" :isItemGroup="true"
      @choose-item="addGroupItem" />

    <!-- Add Brand Dialog -->
    <AddEditBrandDialog v-if="isAddBrandDialogOpen" v-model="isAddBrandDialogOpen" @saveDone="selectNewBrand" />
  </div>
</template>
<script>
import { defineAsyncComponent } from 'vue';
import GInput from "../../../../components/shared/form/GInput.vue";
import GButton from "../../../../components/shared/buttons/GButton.vue";
import TagsPartial from '../Partials/TagsPartial.vue';
import KeywordsPartial from '../Partials/KeywordsPartial.vue';
import { environment } from 'src/boot/axios';

// Lazy-loaded dialog (ALL dialogs must be lazy loaded - CLAUDE.md)
const AddEditBrandDialog = defineAsyncComponent(() =>
  import('../../../dialog/AddEditBrandDialog.vue')
);
const ChooseItemDialog = defineAsyncComponent(() =>
  import('../../../dialog/ChooseItemDialog.vue')
);

export default {
  name: 'SimpleItem',
  components: {
    GInput,
    GButton,
    TagsPartial,
    KeywordsPartial,
    AddEditBrandDialog,
    ChooseItemDialog,
  },
  props: {
    itemInformation: {
      type: Object || null,
      required: false,
    },
  },
  data: () => ({
    isTagHidden: false,
    showUom: false,
    form: {
      itemName: '',
      sku: '',
      isAutoGeneratedSku: true,
      description: '',
      estimatedBuyingPrice: '',
      size: 0,
      unit: '',
      tags: [],
      uom: '',
      sellingPrice: '',
      minimumStockLevel: 0,
      maximumStockLevel: 0,
      categoryId: null,
      keywords: [],
      enabledInPOS: false,
      branchId: null,
      brandId: null,
      itemType: 'INDIVIDUAL_PRODUCT',
      groupItems: [],
    },
    typeOptions: [
      { label: 'Individual Product', value: 'INDIVIDUAL_PRODUCT' },
      { label: 'Item Group', value: 'ITEM_GROUP' },
    ],
    isTagPartialDisplayed: true,
    isKeywordsPartialDisplayed: true,
    isAddBrandDialogOpen: false,
    isChooseItemDialogOpen: false,
    categoryOptions: [],
    branchOptions: [],
    loadingCategories: false,
    loadingBranches: false,
  }),
  watch: {
    form: {
      handler(value) {
        this.$emit('onFormUpdate', {
          type: 'simple',
          data: value,
        });
      },
      deep: true,
    },
    'form.itemName': {
      handler(value) {
        if (this.form.isAutoGeneratedSku) {
          this.form.sku = this.formatCode(value);
        }
      },
    },
    'form.itemType': {
      handler(newVal) {
        // Clear group items when switching away from Item Group
        if (newVal !== 'ITEM_GROUP') {
          this.form.groupItems = [];
        }
      },
    },
  },
  mounted() {
    this.isTagHidden = false;
    this.fetchCategoryOptions();
    this.fetchBranchOptions();
    this.initialize()
  },
  computed: {},
  methods: {
    async fetchCategoryOptions() {
      this.loadingCategories = true;
      try {
        const response = await this.$api.get('/item-category/select-box');
        this.categoryOptions = response.data;
      } catch (error) {
        console.error('Error fetching categories:', error);
      } finally {
        this.loadingCategories = false;
      }
    },
    async fetchBranchOptions() {
      this.loadingBranches = true;
      try {
        const response = await this.$api.get('/branch/select-box');
        this.branchOptions = response.data;
      } catch (error) {
        console.error('Error fetching branches:', error);
      } finally {
        this.loadingBranches = false;
      }
    },
    // Helper function to safely extract raw value from currency objects
    extractRawValue(value, fallback = 0) {
      if (value === null || value === undefined) return fallback;
      if (typeof value === 'object' && value.hasOwnProperty('raw')) return value.raw;
      return value;
    },
    // Helper function to safely extract string value from objects
    extractStringValue(value, fallback = '') {
      if (value === null || value === undefined) return fallback;
      if (typeof value === 'object') {
        // Check for common object properties that might contain the actual value
        if (value.hasOwnProperty('raw')) return String(value.raw);
        if (value.hasOwnProperty('value')) return String(value.value);
        // If it's an object without known properties, return fallback
        return fallback;
      }
      return String(value);
    },
    async initialize() {
      if (this.itemInformation) {
        this.form.itemName = this.extractStringValue(this.itemInformation.name);
        this.form.sku = this.extractStringValue(this.itemInformation.sku);
        this.form.description = this.extractStringValue(this.itemInformation.description);

        // Safely extract estimatedBuyingPrice from either format
        const estimatedPrice = this.itemInformation.formattedEstimatedBuyingPrice ||
          this.itemInformation.estimatedBuyingPrice;
        this.form.estimatedBuyingPrice = this.extractRawValue(estimatedPrice, 0);

        this.form.size = this.itemInformation.rawSize || 0;
        this.form.unit = this.itemInformation.unit;
        this.form.isAutoGeneratedSku = false;
        this.form.tags = this.itemInformation.tags;
        this.form.uom = this.itemInformation.uom;

        // Safely extract all price/number fields
        this.form.sellingPrice = this.extractRawValue(this.itemInformation.sellingPrice, '');
        this.form.minimumStockLevel = this.extractRawValue(this.itemInformation.minimumStockLevel, 0);
        this.form.maximumStockLevel = this.extractRawValue(this.itemInformation.maximumStockLevel, 0);

        this.$refs.tagsPartial.tags = this.itemInformation.tags;
        this.$refs.keywordsPartial.keywords = this.itemInformation.keywords || [];

        // Handle new fields
        this.form.categoryId = this.itemInformation.categoryId || null;
        this.form.brandId = this.itemInformation.brandId || null;
        this.form.enabledInPOS = this.itemInformation.enabledInPOS || false;
        this.form.branchId = this.itemInformation.branchId || null;
        this.form.itemType = this.itemInformation.itemType || 'INDIVIDUAL_PRODUCT';

        // Load group items if editing an item group
        if (this.form.itemType === 'ITEM_GROUP') {
          // Map backend format (nested item) to frontend format (flat)
          // Normalize all fields to ensure they're primitive values
          this.form.groupItems = (this.itemInformation.groupItems || []).map(gi => ({
            id: gi.item?.id || gi.itemId,
            name: this.extractStringValue(gi.item?.name || ''),
            sku: this.extractStringValue(gi.item?.sku || ''),
            quantity: Number(gi.quantity) || 1
          }));
        }

        // Set brand after refs are ready
        await this.$nextTick();
        if (this.form.brandId && this.$refs.brandSelect) {
          await this.$refs.brandSelect.setAutoSelect(this.form.brandId);
        }

        if (this.itemInformation.hasOwnProperty('parent') && this.itemInformation.parent) {
          this.isTagHidden = true;
        }
        else {
          this.showUom = true
        }
      }
      else {
        this.showUom = true
      }
    },
    onCheckboxTicked(val) {
      this.form.isAutoGeneratedSku = val;

      if (!val) {
        this.form.sku = '';
      }
    },
    onTagUpdated(val) {
      this.form.tags = val;
    },
    onKeywordUpdated(val) {
      this.form.keywords = val;
    },
    fillData() {
      if (environment === 'development') {
        const randomNumber = Math.floor(Math.random() * 1000);
        const itemName = `Item-${randomNumber}`;

        this.form = {
          ...this.form,
          itemName: itemName,
          sku: itemName,
          description: `Random Description ${randomNumber}`,
          estimatedBuyingPrice: randomNumber,
          size: randomNumber,
          sellingPrice: randomNumber * 1.5,
          minimumStockLevel: 10,
          maximumStockLevel: 100,
        };

        this.$q.notify({
          color: 'grey-8',
          message: 'Data filled successfully',
          position: 'top',
        });
      }
    },
    showBrandAddDialog() {
      this.isAddBrandDialogOpen = true;
    },
    async selectNewBrand(data) {
      const autoSelect = data.id;
      await this.$refs.brandSelect.refreshSelectOptions(autoSelect);
      this.form.brandId = autoSelect;
    },
    addGroupItem(item) {
      // Validate item type - only INDIVIDUAL_PRODUCT items can be added to groups
      if (item.itemType === 'ITEM_GROUP') {
        this.$q.notify({
          color: 'negative',
          message: 'Cannot add Item Groups to another Item Group. Only Individual Products are allowed.',
          position: 'top'
        });
        return;
      }

      // Check if item already exists
      const exists = this.form.groupItems.some(i => i.id === item.id);
      if (exists) {
        this.$q.notify({
          color: 'warning',
          message: 'This item is already in the group',
          position: 'top'
        });
        return;
      }

      // Normalize item data to ensure all fields are primitive values
      // Variation items may have objects for text fields instead of strings
      this.form.groupItems.push({
        id: item.id,
        name: this.extractStringValue(item.name),
        sku: this.extractStringValue(item.sku),
        quantity: Number(item.quantity) || 1,
      });
    },
    removeGroupItem(index) {
      this.form.groupItems.splice(index, 1);
    },
  },
};
</script>

<style scoped lang="scss">
.example-column-vertical-alignment {
  max-height: 75vh;
  overflow-y: auto;
  scrollbar-width: thin;
  scrollbar-color: var(--q-scroll-background-track) var(--q-scroll-background);
}
</style>
