name: Deploy to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'frontends/frontend-main/**'
      - 'frontends/frontend-gate-app/**'
      - 'frontends/frontend-guardian-app/**'
      - 'backend/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-main-changed: ${{ steps.changes.outputs.frontend-main }}
      gate-app-changed: ${{ steps.changes.outputs.gate-app }}
      guardian-app-changed: ${{ steps.changes.outputs.guardian-app }}
      backend-changed: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend-main:
              - 'frontends/frontend-main/**'
              - 'package.json'
              - 'yarn.lock'
            gate-app:
              - 'frontends/frontend-gate-app/**'
              - 'package.json'
              - 'yarn.lock'
            guardian-app:
              - 'frontends/frontend-guardian-app/**'
              - 'package.json'
              - 'yarn.lock'
            backend:
              - 'backend/**'
              - 'package.json'
              - 'yarn.lock'

  deploy-frontend-main:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-main-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Copy staging environment config
        run: |
          cd frontends/frontend-main
          cp environment/env.staging .env
          echo "Environment file configured:"
          cat .env

      - name: Deploy Frontend Main to Vercel
        run: |
          cd frontends/frontend-main
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND_MAIN }}

  deploy-gate-app:
    needs: detect-changes
    if: needs.detect-changes.outputs.gate-app-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy Gate App to Vercel
        run: |
          cd frontends/frontend-gate-app
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_GATE_APP }}

  deploy-guardian-app:
    needs: detect-changes
    if: needs.detect-changes.outputs.guardian-app-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy Guardian App to Vercel
        run: |
          cd frontends/frontend-guardian-app
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_APP }}

  build-and-deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ante-backend-staging
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: production-alpine

      - name: Trigger DigitalOcean deployment
        run: |
          echo "Triggering deployment for app ${{ secrets.DO_APP_ID_STAGING }}..."

          RESPONSE=$(curl -s -X POST \
            "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID_STAGING }}/deployments" \
            -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"force_build": false}')

          DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r '.deployment.id // empty')

          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "Error: Failed to trigger deployment"
            echo "$RESPONSE" | jq '.'
            exit 1
          fi

          echo "Deployment triggered successfully!"
          echo "Deployment ID: $DEPLOYMENT_ID"
          echo "View deployment: https://cloud.digitalocean.com/apps/${{ secrets.DO_APP_ID_STAGING }}/deployments/$DEPLOYMENT_ID"
